spring.application.name=training_curriculum_java
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/training_curriculum_java
spring.datasource.username=keisuke
spring.datasource.password= wafuka0806
spring.flyway.baselineOnMigrate=true